version: '3.8'

services:
  mcp-server:
    build:
      context: .
      dockerfile: Containerfile
    ports:
      - "8000:8000"
    environment:
      - QDRANT_URL=http://qdrant:6333
      - COLLECTION_NAME=dev-collection
      - EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2
    depends_on:
      - qdrant
    user: "1000:1000"  # Explicit user mapping for rootless mode

  qdrant:
    image: docker.io/qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    user: "1000:1000"  # Explicit user mapping for rootless mode

volumes:
  qdrant_data:
    driver: local 